apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: frontend
  namespace: mariamnassar-dev
spec:
  source:
    git:
      uri: https://github.com/sarahhgamal/eventPlanner-frontend
  strategy:
    dockerStrategy:
      dockerfilePath: Dockerfile
  output:
    to:
      kind: ImageStreamTag
      name: frontend:latest
---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: frontend
  namespace: mariamnassar-dev
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: mariamnassar-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: image-registry.openshift-image-registry.svc:5000/mariamnassar-dev/frontend:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: mariamnassar-dev
spec:
  selector:
    app: frontend
  ports:
  - port: 80
    targetPort: 80
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: frontend
  namespace: mariamnassar-dev
spec:
  to:
    kind: Service
    name: frontend
  port:
    targetPort: 80